#Local Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    
  servlet:
    multipart:
      max-file-size: 3000MB
      max-request-size: 3000MB
    
file:
 server:
  path: C:\FTP Server\
  

